Don't set read/write capacity in PAY_PER_REQUEST billing mode
This causes errors at plan-time now:

Error: 2 errors occurred:
	* read_capacity can not be set when billing_mode is "PAY_PER_REQUEST"
	* write_capacity can not be set when billing_mode is "PAY_PER_REQUEST"

  with module.dynamodb_table.aws_dynamodb_table.default[0],
  on .terraform/modules/dynamodb_table/main.tf line 46, in resource "aws_dynamodb_table" "default":
  46: resource "aws_dynamodb_table" "default" {